# Étape 1 : Build (compilation TypeScript)
FROM node:22 AS builder

WORKDIR /app

# Copier uniquement les fichiers de dépendances d'abord
# COPY ../package*.json ./
# COPY ../tsconfig.json ./
# COPY ../**.json ./

# RUN ls

# RUN npm ci

# Copier le reste du code source
# COPY ../src/**/* ./src/

# (Adapter si le point d'entrée diffère)
# CMD ["npm", "run", "compile:npx"]
CMD [ "bash" ]