# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
        
name: Bedy90 - Riot Entity - Deploy (Alpha)

on:   
  release:
    types: [published]

  # Manual action
  workflow_dispatch:

permissions:
   contents: read
   packages: write  
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    # Setup .npmrc file to publish to npm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
         # Defaults to the user or organization that owns the workflow file
        scope: '@bedy90'
        
    - name: Install Typescript
      run: npm install typescript@5.3.3 -g
      
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run compile:npx

    # - name: Publish on Github NPM package
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # TODO: Delete current alpha if exists
    # - name: Unpublish if exists
    #   run: |
    #     PACKAGE_NAME=$(jq -r '.name' package.json)
    #     PACKAGE_VERSION=$(jq -r '.version' package.json)
    #     if npm show $PACKAGE_NAME@$PACKAGE_VERSION ; then
    #       npm unpublish $PACKAGE_NAME@$PACKAGE_VERSION --force
    #     fi

    - uses: JS-DevTools/npm-publish@v3
      id : "publishTag"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: "https://npm.pkg.github.com"
        tag: alpha

    - if: ${{ steps.publishTag.outputs.type }}
      run: echo "Version ${{ steps.publishTag.outputs.version }} has published !"